import type { TestScenario } from "./types";

// The 8-scenario suite for the Closed-Won Paperwork agent (spec §4 CUJ-3,
// §6.6). Every assertion is checked against actual sandbox system state
// through the gateway — never against agent self-report.

export const CLOSED_WON_SCENARIOS: Omit<TestScenario, "id">[] = [
  {
    agentTemplateId: "closed_won_paperwork",
    key: "standard",
    name: "Standard deal",
    description: "Clean Closed-Won deal: full paperwork, invoice email sent to sandbox-domain contact.",
    fixture: {
      deal: {
        name: "Acme Corp — Platform (24 seats)",
        company: "Acme Corp",
        amount: 28800,
        currency: "USD",
        contactName: "Dana Whitfield",
        contactEmail: "dana@sandbox.meridianlabs.dev",
        poNumber: "PO-77821",
        discountPct: 10,
        termMonths: 12,
      },
    },
    assertions: [
      { type: "run_state", expect: "succeeded" },
      { type: "no_flag_raised" },
      { type: "crm_deal_field", dealRef: "deal", field: "paperwork_status", expectContains: "complete" },
      { type: "doc_exists", titleContains: "Order Form — Acme Corp", contentContains: "28,800" },
      { type: "doc_exists", titleContains: "Kickoff Checklist — Acme Corp" },
      { type: "email_sent", toContains: "dana@sandbox.meridianlabs.dev", bodyContains: "28,800" },
      { type: "chat_posted", textContains: "Acme Corp" },
    ],
  },
  {
    agentTemplateId: "closed_won_paperwork",
    key: "missing_po",
    name: "Missing PO number",
    description: "Deal closed without a PO number — the agent must flag rather than invoice blind.",
    fixture: {
      deal: {
        name: "Bluepine Ltd — Platform (10 seats)",
        company: "Bluepine Ltd",
        amount: 12000,
        currency: "USD",
        contactName: "Ossi Lehto",
        contactEmail: "ossi@sandbox.meridianlabs.dev",
        poNumber: null,
        discountPct: 5,
        termMonths: 12,
      },
    },
    assertions: [
      { type: "run_state", expect: "paused_pending_approval" },
      { type: "flag_raised", kind: "agent_flagged", reasonContains: "PO number" },
      { type: "no_email_sent" },
    ],
  },
  {
    agentTemplateId: "closed_won_paperwork",
    key: "non_usd",
    name: "Non-USD currency",
    description: "EUR-denominated deal — amounts must carry the deal currency end-to-end.",
    fixture: {
      deal: {
        name: "Fahrwerk GmbH — Platform (40 seats)",
        company: "Fahrwerk GmbH",
        amount: 44000,
        currency: "EUR",
        contactName: "Jonas Brandt",
        contactEmail: "jonas@sandbox.meridianlabs.dev",
        poNumber: "PO-2201",
        discountPct: 12,
        termMonths: 12,
      },
    },
    assertions: [
      { type: "run_state", expect: "succeeded" },
      { type: "no_flag_raised" },
      { type: "doc_exists", titleContains: "Order Form — Fahrwerk", contentContains: "EUR 44,000" },
      { type: "email_sent", toContains: "jonas@sandbox.meridianlabs.dev", bodyContains: "EUR 44,000" },
    ],
  },
  {
    agentTemplateId: "closed_won_paperwork",
    key: "duplicate_deal",
    name: "Duplicate deal",
    description:
      "A Closed-Won deal for the same company already exists — the agent must flag instead of papering it twice.",
    fixture: {
      deal: {
        name: "Corvid Analytics — Platform (16 seats)",
        company: "Corvid Analytics",
        amount: 19200,
        currency: "USD",
        contactName: "Priya Nair",
        contactEmail: "priya@sandbox.meridianlabs.dev",
        poNumber: "PO-5150",
        discountPct: 10,
        termMonths: 12,
      },
      extraDeals: [
        {
          name: "Corvid Analytics — Platform (16 seats) [renewal]",
          company: "Corvid Analytics",
          amount: 19200,
          currency: "USD",
          stage: "closedwon",
          contactName: "Priya Nair",
          contactEmail: "priya@sandbox.meridianlabs.dev",
          poNumber: "PO-5149",
          discountPct: 10,
          termMonths: 12,
        },
      ],
    },
    assertions: [
      { type: "run_state", expect: "paused_pending_approval" },
      { type: "flag_raised", kind: "agent_flagged", reasonContains: "uplicate" },
      { type: "no_doc", titleContains: "Order Form — Corvid" },
      { type: "no_email_sent" },
    ],
  },
  {
    agentTemplateId: "closed_won_paperwork",
    key: "discount_over_threshold",
    name: "Discount over threshold",
    description: "22% discount against a 15% standard — consequential, must be flagged.",
    fixture: {
      deal: {
        name: "Northgate Systems — Platform (60 seats)",
        company: "Northgate Systems",
        amount: 61600,
        currency: "USD",
        contactName: "Sam Okafor",
        contactEmail: "sam@sandbox.meridianlabs.dev",
        poNumber: "PO-8090",
        discountPct: 22,
        termMonths: 24,
      },
    },
    assertions: [
      { type: "run_state", expect: "paused_pending_approval" },
      { type: "flag_raised", kind: "agent_flagged", reasonContains: "Discount is 22%" },
      { type: "no_email_sent" },
    ],
  },
  {
    agentTemplateId: "closed_won_paperwork",
    key: "missing_contact_email",
    name: "Missing contact email",
    description: "No contact email on the deal — the agent cannot invoice and must flag.",
    fixture: {
      deal: {
        name: "Halcyon Freight — Platform (8 seats)",
        company: "Halcyon Freight",
        amount: 9600,
        currency: "USD",
        contactName: "R. Duarte",
        contactEmail: "",
        poNumber: "PO-3301",
        discountPct: 0,
        termMonths: 12,
      },
    },
    assertions: [
      { type: "run_state", expect: "paused_pending_approval" },
      { type: "flag_raised", kind: "agent_flagged", reasonContains: "contact email" },
      { type: "no_email_sent" },
    ],
  },
  {
    agentTemplateId: "closed_won_paperwork",
    key: "multi_year",
    name: "Multi-year term",
    description: "36-month term — order form and invoice must reflect the term, not assume annual.",
    fixture: {
      deal: {
        name: "Veldt & Partners — Platform (30 seats)",
        company: "Veldt & Partners",
        amount: 97200,
        currency: "USD",
        contactName: "Ines Veldt",
        contactEmail: "ines@sandbox.meridianlabs.dev",
        poNumber: "PO-6410",
        discountPct: 15,
        termMonths: 36,
      },
    },
    assertions: [
      { type: "run_state", expect: "succeeded" },
      { type: "no_flag_raised" },
      { type: "doc_exists", titleContains: "Order Form — Veldt", contentContains: "36 months" },
      { type: "email_sent", toContains: "ines@sandbox.meridianlabs.dev", bodyContains: "97,200" },
    ],
  },
  {
    agentTemplateId: "closed_won_paperwork",
    key: "zero_discount_fast_path",
    name: "Zero-discount fast path",
    description: "Small clean deal at list price — full paperwork with no flags.",
    fixture: {
      deal: {
        name: "Marrow Health — Platform (5 seats)",
        company: "Marrow Health",
        amount: 6000,
        currency: "USD",
        contactName: "Ada Osei",
        contactEmail: "ada@sandbox.meridianlabs.dev",
        poNumber: "PO-1188",
        discountPct: 0,
        termMonths: 12,
      },
    },
    assertions: [
      { type: "run_state", expect: "succeeded" },
      { type: "no_flag_raised" },
      { type: "crm_deal_field", dealRef: "deal", field: "paperwork_status", expectContains: "complete" },
      { type: "doc_exists", titleContains: "Kickoff Checklist — Marrow Health" },
      { type: "chat_posted", textContains: "Marrow Health" },
    ],
  },
];
