# Remote state for the Lightsail demo console.
#
# The session signing key and both database passwords are generated by the
# apply and therefore exist in state, so state lives in the same encrypted,
# access-controlled bucket the production stack uses — a different key, the
# same protection. A demo stamp generates real credentials; local state would
# leave them in the working directory.
terraform {
  backend "s3" {
    bucket       = "deployconvoy"
    key          = "website/console/demo/terraform.tfstate"
    region       = "us-east-2"
    kms_key_id   = "arn:aws:kms:us-east-2:327998106824:key/15a95248-841d-4ad9-af4e-455bbf56f9ee"
    encrypt      = true
    use_lockfile = true
  }
}
