# Remote state for the production console.
#
# The session signing key and both database passwords are generated by the
# apply and therefore exist in state, so state lives in an encrypted,
# access-controlled S3 bucket under a customer-managed KMS key.
#
# The backend region is deliberately not the region the console runs in: the
# state bucket and its key live in us-east-2, while the console itself is
# stamped in us-west-2 (see prod.tfvars). A backend in a different region from
# the provider is normal and supported — the two are unrelated.
terraform {
  backend "s3" {
    bucket       = "deployconvoy"
    key          = "website/console/prod/terraform.tfstate"
    region       = "us-east-2"
    kms_key_id   = "arn:aws:kms:us-east-2:327998106824:key/15a95248-841d-4ad9-af4e-455bbf56f9ee"
    encrypt      = true
    use_lockfile = true
  }
}
