/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents/{agent_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Schedule */
        get: operations["get_agent_schedule_agents__agent_id__schedule_get"];
        /**
         * Put Agent Schedule
         * @description Create or replace the agent's schedule. The run template freezes what
         *     the console resolved at save time; the tenant comes from the
         *     authenticated caller, never the body. Firings create runs through the
         *     normal POST /runs path with started_via="schedule".
         */
        put: operations["put_agent_schedule_agents__agent_id__schedule_put"];
        post?: never;
        /** Remove Agent Schedule */
        delete: operations["remove_agent_schedule_agents__agent_id__schedule_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Tenant-scoped run list, newest first, from projections only. This is
         *     the console's run directory — no client should have to remember run ids
         *     it created (the website's in-process map retires against this).
         */
        get: operations["list_runs_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/clock/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance Clock
         * @description Fast-forward a rehearsal run's virtual clock, resolving every virtual
         *     timer with a deadline at or before the target. Guarded twice: only
         *     sandbox-kind bindings running a virtual clock accept advances (the
         *     workflow re-checks and drops anything else), and time never moves
         *     backward. The advance is an audited external mutation — the signal
         *     carries the verified actor, and the events its resolved timers emit
         *     attribute it.
         */
        post: operations["advance_clock_runs__run_id__clock_advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/land": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Land Run */
        post: operations["land_run_runs__run_id__land_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Run */
        post: operations["pause_run_runs__run_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/plan/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Plan
         * @description Approve or reject the plan version awaiting approval. The supplied
         *     version must match the live plan so decisions can never target a plan
         *     the human did not review; the workflow re-checks and drops mismatches.
         */
        post: operations["approve_plan_runs__run_id__plan_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/steer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Steer Run
         * @description Append one steer to the run's mailbox; the workflow loop drains it
         *     into the next turn.
         */
        post: operations["steer_run_runs__run_id__steer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/steps/{step_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Respond To Gate
         * @description Answer exactly one step's open human gate. Responding to a step that
         *     is not blocked on a human is a clean conflict; the workflow re-checks and
         *     drops stale answers. A response carrying `at_virtual` is a scheduled
         *     simulated answer, so it may target a gate that has not opened yet.
         */
        post: operations["respond_to_gate_runs__run_id__steps__step_id__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentScheduleRequest */
        AgentScheduleRequest: {
            schedule: components["schemas"]["AgentScheduleSpec"];
            template: components["schemas"]["ScheduleRunTemplateRequest"];
        };
        /**
         * AgentScheduleSpec
         * @description What the console saves: a standard 5-field cron in a named timezone,
         *     plus whether the schedule is live.
         */
        AgentScheduleSpec: {
            /** Cron */
            cron: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** AgentScheduleView */
        AgentScheduleView: {
            /** Agent Id */
            agent_id: string;
            /** Cron */
            cron: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Next Run Times
             * @default []
             */
            next_run_times: string[];
            /** Timezone */
            timezone: string;
        };
        /**
         * ApprovePlanRequest
         * @description Approve or reject the plan version awaiting approval. The version pin
         *     guarantees the decision targets the plan the human actually reviewed;
         *     rejections must say why.
         */
        ApprovePlanRequest: {
            /**
             * Approve
             * @default true
             */
            approve: boolean;
            /** Plan Version */
            plan_version: number;
            /** Reason */
            reason?: string | null;
        };
        /** BudgetView */
        BudgetView: {
            /** Cap Usd */
            cap_usd?: string | null;
            /** Reserved Usd */
            reserved_usd?: string | null;
            /** Spent Usd */
            spent_usd?: string | null;
        };
        /**
         * ClockAdvanceRequest
         * @description Move a virtual-clock rehearsal run's time forward to `to`
         *     (timezone-aware, or it is rejected).
         */
        ClockAdvanceRequest: {
            /**
             * To
             * Format: date-time
             */
            to: string;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Agent Id */
            agent_id?: string | null;
            /**
             * Budget Usd
             * @default 10
             */
            budget_usd: number | string;
            /**
             * Environment Id
             * @default stub-local
             */
            environment_id: string;
            fixture_fanout?: components["schemas"]["FanoutFixture"] | null;
            /**
             * Fixture Gates
             * @default {}
             */
            fixture_gates: {
                [key: string]: components["schemas"]["HumanGate"];
            };
            /** Goal */
            goal: string;
            /**
             * Instructions
             * @default []
             */
            instructions: string[];
            /**
             * Max Children
             * @default 5
             */
            max_children: number;
            /** Model */
            model?: string | null;
            policy?: components["schemas"]["RunPolicy"] | null;
            /** Run Id */
            run_id?: string | null;
            /** Started By */
            started_by?: string | null;
            /**
             * Started Via
             * @default manual
             * @enum {string}
             */
            started_via: "manual" | "schedule" | "event";
            /**
             * Success Criteria
             * @default []
             */
            success_criteria: string[];
            /**
             * Tools
             * @default []
             */
            tools: string[];
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
        };
        /**
         * ExecutionSessionView
         * @description Observable cloud compute/checkpoint state for a run.
         */
        ExecutionSessionView: {
            /** Environment Id */
            environment_id: string;
            /**
             * Generation
             * @default 0
             */
            generation: number;
            /** Latest Checkpoint Id */
            latest_checkpoint_id?: string | null;
            /** Latest Snapshot Ref */
            latest_snapshot_ref?: {
                [key: string]: unknown;
            } | null;
            /** Sandbox Id */
            sandbox_id?: string | null;
            /** Sandbox Provider */
            sandbox_provider?: string | null;
            /** Sandbox Template */
            sandbox_template?: string | null;
            /** Status */
            status: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * FanoutFixture
         * @description Fixture-plan fan-out request: a group of `size` subagent members
         *     between the investigate step and the summarize step (which becomes the
         *     join). Members carry `budget_slice` as their reservation and are marked
         *     optional so a tolerated member failure still lands as a valid partial
         *     completion; the join stays required. `child_layer` exists so tests can
         *     craft depth-guard violations.
         */
        FanoutFixture: {
            /** Budget Slice */
            budget_slice?: number | string | null;
            /**
             * Child Layer
             * @default 1
             */
            child_layer: number;
            /** Size */
            size: number;
        };
        /**
         * GateRespondRequest
         * @description Answer one step's open human gate. `at_virtual` scripts a simulated
         *     human on virtual-clock rehearsal runs: the answer is delivered when
         *     virtual time reaches that instant (timezone-aware, or it is rejected).
         */
        GateRespondRequest: {
            /** At Virtual */
            at_virtual?: string | null;
            /** Response */
            response: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HumanGate */
        HumanGate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "approval" | "input" | "action";
            /**
             * On Timeout
             * @default pause
             * @enum {string}
             */
            on_timeout: "pause" | "skip" | "fail";
            /** Prompt */
            prompt: string;
            /** Timeout */
            timeout?: string | null;
        };
        /**
         * RunListResponse
         * @description Newest-first, keyset-paginated: pass `next_created_before` back as
         *     `created_before` to fetch the next page; null means the list is done.
         */
        RunListResponse: {
            /** Next Created Before */
            next_created_before?: string | null;
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /** RunPolicy */
        RunPolicy: {
            /**
             * Approval Scope
             * @default major_revisions
             * @enum {string}
             */
            approval_scope: "initial" | "major_revisions" | "all_revisions";
            /**
             * Max Depth
             * @default 1
             */
            max_depth: number;
            /**
             * Max Parallel
             * @default 5
             */
            max_parallel: number;
            /**
             * Max Steps
             * @default 50
             */
            max_steps: number;
            /**
             * On Budget Exhausted
             * @default pause
             * @enum {string}
             */
            on_budget_exhausted: "pause" | "land" | "abort";
            /**
             * On Group Partial Failure
             * @default join_with_partials
             * @enum {string}
             */
            on_group_partial_failure: "join_with_partials" | "block_on_human" | "fail_group";
            /**
             * Plan Shape
             * @default linear_fanout
             * @enum {string}
             */
            plan_shape: "linear" | "linear_fanout" | "dag";
            /**
             * Require Plan Approval
             * @default true
             */
            require_plan_approval: boolean;
        };
        /**
         * RunSummary
         * @description One row of GET /runs — the list shape the console renders. Full plan,
         *     land report, and steps stay on GET /runs/{run_id}.
         */
        RunSummary: {
            /** Agent Id */
            agent_id?: string | null;
            budget?: components["schemas"]["BudgetView"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Environment Id
             * @default
             */
            environment_id: string;
            execution_session?: components["schemas"]["ExecutionSessionView"] | null;
            /** Goal */
            goal: string;
            /** Land Report */
            land_report?: {
                [key: string]: unknown;
            } | null;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Run Id */
            run_id: string;
            /** Started By */
            started_by?: string | null;
            /**
             * Started Via
             * @default manual
             */
            started_via: string;
            /** Status */
            status: string;
            /**
             * Steps Done
             * @default 0
             */
            steps_done: number;
            /**
             * Steps Total
             * @default 0
             */
            steps_total: number;
            /** Tenant Id */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RunView
         * @description Served from Postgres projections only — never from Temporal. Subagent
         *     child runs are rows of their own, linked back by `parent_run_id`.
         */
        RunView: {
            /** Agent Id */
            agent_id?: string | null;
            budget?: components["schemas"]["BudgetView"] | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Environment Id
             * @default
             */
            environment_id: string;
            execution_session?: components["schemas"]["ExecutionSessionView"] | null;
            /** Goal */
            goal: string;
            /** Land Report */
            land_report?: {
                [key: string]: unknown;
            } | null;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Plan */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: string;
            /** Started By */
            started_by?: string | null;
            /**
             * Started Via
             * @default manual
             */
            started_via: string;
            /** Status */
            status: string;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["StepView"][];
            /** Tenant Id */
            tenant_id: string;
        };
        /**
         * ScheduleRunTemplateRequest
         * @description The run the schedule should start on each firing — what the console
         *     resolved from the agent at save time. Tenant is taken from the
         *     authenticated caller, never this body.
         */
        ScheduleRunTemplateRequest: {
            /** Budget Usd */
            budget_usd: string;
            /** Environment Id */
            environment_id: string;
            /** Goal */
            goal: string;
            /**
             * Instructions
             * @default []
             */
            instructions: string[];
            /** Started By */
            started_by?: string | null;
            /**
             * Tools
             * @default []
             */
            tools: string[];
        };
        /** SignalResponse */
        SignalResponse: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
            /** Run Id */
            run_id: string;
            /** Signal */
            signal: string;
        };
        /**
         * SteerRequest
         * @description A steer for the run's mailbox: a note rides into the next turn's
         *     context; a redirect additionally forces the agent to assess the plan
         *     against it.
         */
        SteerRequest: {
            /** Body */
            body: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "note" | "redirect";
        };
        /** SteerResponse */
        SteerResponse: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "note" | "redirect";
            /** Run Id */
            run_id: string;
            /** Steer Id */
            steer_id: string;
        };
        /** StepView */
        StepView: {
            /**
             * Attempt
             * @default 0
             */
            attempt: number;
            /** Cost Usd */
            cost_usd?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Model Used */
            model_used?: string | null;
            /** Status */
            status: string;
            /** Step Id */
            step_id: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_agent_schedule_agents__agent_id__schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentScheduleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_agent_schedule_agents__agent_id__schedule_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentScheduleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_agent_schedule_agents__agent_id__schedule_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                status?: string | null;
                agent_id?: string | null;
                created_before?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_clock_runs__run_id__clock_advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClockAdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    land_run_runs__run_id__land_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_run_runs__run_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_runs__run_id__plan_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    steer_run_runs__run_id__steer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SteerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SteerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_to_gate_runs__run_id__steps__step_id__respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateRespondRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
