import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { demoDocument, mockApi, noOverflow, PROJECT } from "./support/configurations";
import type { ConvoyWorkspace } from "@/lib/configurations/types";

test("project assignment preserves an existing setup and results across navigation and reload", async ({ page }, info) => {
  const document = demoDocument();
  const config = document.configurations[2];
  const { documents } = await mockApi(page, { document });
  await page.route(/\/api\/platform\/(robot-profiles|fleets|robot-connections|deployments)(\?|$)/, route => route.fulfill({ json: [] }));
  await page.goto(`/app/projects/${PROJECT}?section=configurations`);
  await page.getByRole("button", { name: "Add a saved configuration" }).click();
  const dialog = page.getByRole("dialog", { name: "Add a saved configuration" });
  await dialog.getByLabel("Saved configuration").selectOption(config.id);
  await dialog.getByRole("button", { name: "Add to project", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const saved = page.getByRole("region", { name: "Saved configurations", exact: true });
  await expect(saved.getByRole("link", { name: new RegExp(config.name) })).toBeVisible();
  const stored = documents.document as ConvoyWorkspace;
  expect(stored.configurations.find(c => c.id === config.id)?.projectId).toBe(PROJECT);
  for (const key of ["robots", "runs", "rollouts", "traces", "logs"] as const) expect(stored[key]).toEqual(document[key]);
  expect(stored.configurations[0]).toEqual(document.configurations[0]);
  // The assigned configuration opens in the Configurations frame, with its own trail and no project navigation.
  await saved.getByRole("link", { name: new RegExp(config.name) }).click();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText(config.name);
  await expect(page.getByRole("navigation", { name: "Breadcrumb" }).getByRole("listitem")).toHaveText(["Configurations", config.name]);
  await expect(page.getByRole("navigation", { name: "Project sections" })).toHaveCount(0);
  await page.goto(`/app/projects/${PROJECT}?section=runs`);
  const results = page.getByRole("region", { name: "Saved evaluations" });
  await expect(results.getByText(config.name, { exact: true })).toBeVisible();
  await results.getByRole("link", { name: "Sim runner" }).click();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Sim runner");
  await expect(page.getByRole("navigation", { name: "Breadcrumb" }).getByRole("listitem")).toHaveText(["Configurations", config.name, "Sim runner"]);
  await expect(page.getByRole("navigation", { name: "Project sections" })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Sim runner");
  await page.locator("header.cv-bar").getByRole("navigation", { name: "Workspace" }).getByRole("link", { name: "Projects" }).click();
  await page.getByRole("region", { name: "Your projects" }).getByRole("link", { name: /Contract project/ }).click();
  await expect(page.getByRole("navigation", { name: "Project sections" }).getByRole("link", { name: "Overview", exact: true })).toHaveAttribute("aria-current", "page");
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow(page);
  await page.screenshot({ path: info.outputPath("project-overview-mobile.png"), fullPage: true });
});

test("project model setup is a draft and never dispatches execution", async ({ page }) => {
  const { documents, platform } = await mockApi(page, { document: null });
  await page.goto(`/app/configurations/new?project_id=${PROJECT}&setup=draft`);
  await page.getByRole("textbox", { name: "Name", exact: true }).fill("New paired setup");
  await page.getByRole("textbox", { name: "Robot", exact: true }).fill("Custom arm");
  await page.getByLabel("Edge model", { exact: true }).fill("SmolVLA");
  await page.getByRole("textbox", { name: "Cloud model", exact: true }).fill("Cloud planner");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("New paired setup");
  const config = (documents.document as ConvoyWorkspace).configurations[0];
  expect(config.projectId).toBe(PROJECT);
  expect(config.status).toBe("draft");
  expect(platform.paths.some(path => path === "deployments" || path.includes("/missions"))).toBe(false);
  await expect(page.getByRole("navigation", { name: "Project sections" })).toHaveCount(0);
  await expect(page.getByRole("navigation", { name: "Breadcrumb" }).getByRole("listitem")).toHaveText(["Configurations", "New paired setup"]);
});
