# Remote state backend. REQUIRED for a real console: the session signing key
# and both database passwords are generated by the apply and therefore exist
# in state, so state must live in an encrypted, access-controlled S3 backend —
# never on a laptop.
#
# Copy this root per console deployment (stacks/<name>/), then uncomment and
# fill in before `terraform init`:
#
# terraform {
#   backend "s3" {
#     bucket       = "convoy-terraform-state"
#     key          = "website/console/<name>/terraform.tfstate"
#     region       = "us-east-1"
#     kms_key_id   = "arn:aws:kms:us-east-1:<ops-account>:key/<state-key-id>"
#     encrypt      = true
#     use_lockfile = true
#   }
# }
